---
title: "0308-deseq2"
output: html_document
---
```{r}
#set working directory to the project for wherever it is stored on your computer
setwd("/Volumes/Samsung USB/Megan-project/")
```

```{r run once}
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(version = "3.12")
biocLite("DESeq2")
library(DESeq2)
```



```{r}
#load in count data, you will need to change the read line to the absolute path
setwd("/Volumes/Samsung USB/Megan-project/")
options(scipen = 999)
data <- read.delim("./analyses/kallisto.isoform.counts.matrix")
rownames(data) <- data$Feature
#ensures all data as integer
#data <- round(data, digits = 0)
```


```{r}
#build objects; specify which columns are in groups
deseq2.colData <- data.frame(condition=factor(c(rep("Control", 2), rep("Estradiol", 2))), 
                             type=factor(rep("single-read", 4)))
rownames(deseq2.colData) <- colnames(data)
deseq2.dds <- DESeqDataSetFromMatrix(countData = data,
                                     colData = deseq2.colData, 
                                     design = ~ condition)

```

```{r}
#run analysis
deseq2.dds <- DESeq(deseq2.dds)
deseq2.res <- results(deseq2.dds)
#deseq2.res <- deseq2.res[order(rownames(deseq2.res)) , ]

head(deseq2.res)
```

```{r}
#Count number of hits with adjusted p-value less then 0.05
dim(deseq2.res[!is.na(deseq2.res$padj) & deseq2.res$padj <= 0.05, ])

tmp <- deseq2.res
```

```{r volcano}
# The main plot
plot(tmp$baseMean, tmp$log2FoldChange, pch=20, cex=0.45, ylim=c(-3, 3), log="x", col="darkgray",
     main="DEG Estradiol versus Control  (pval <= 0.05)",
     xlab="mean of normalized counts",
     ylab="Log2 Fold Change")
# Getting the significant points and plotting them again so they're a different color
tmp.sig <- deseq2.res[!is.na(deseq2.res$padj) & deseq2.res$padj <= 0.05, ]
points(tmp.sig$baseMean, tmp.sig$log2FoldChange, pch=20, cex=0.45, col="red")
# 2 FC lines
abline(h=c(-1,1), col="blue")
```
```{r}
#load libraries for heatmap
library("RColorBrewer")
library( "genefilter" )
library("pheatmap")
```
```{r}
#Regularized log transformation
rld <- rlog( deseq2.dds )
#Get 25 top varying genes
topVarGenes <- head( order( rowVars( assay(rld) ), decreasing=TRUE ), 25)
```

```{r}
#make a subset of the log transformed counts for just the top 25 varying genes
top25Counts<-assay(rld)[topVarGenes,]
#Use pheatmap function to draw a heatmap
#INCLUDE NEXT LINE IF YOU WANT TO SAVE THE FIGURE IN A FILE
#pdf(file="gene.heatmap.pdf")
pheatmap(top25Counts,scale = "row")
#INCLUDE NEXT LINE IF YOU WANT TO SAVE THE FIGURE IN A FILE
#dev.off()
```
```{r}
#PLOT PCA
#INCLUDE NEXT LINE IF YOU WANT TO SAVE THE FIGURE IN A FILE
#pdf(file="pca.pdf")
print(plotPCA(rld, intgroup=c("Estradiol")))
#INCLUDE NEXT LINE IF YOU WANT TO SAVE THE FIGURE IN A FILE
#dev.off()
```


```{r}
#write.table(tmp.sig, "", row.names = T)

```


